### ISSUE TITLE
Régler le problèmes de target="_blank"

### ISSUE THREAD

**Issue by Cervangirard** [ThinkR-open/golemverse.org#3]
ça ouvre un nouvel onglet mais met à jour l'onglet actif aussi

![image](https://user-images.githubusercontent.com/37626302/71258652-0c044000-2337-11ea-8f84-27deea568415.png)

**Comment by statnmap** [comment]
Ça vient du thème apparemment. 
J'ai posé une issue: https://github.com/gcushen/hugo-academic/issues/1511

**Comment by statnmap** [comment]
Done here: https://github.com/ThinkR-open/golemverse.org/pull/26
