### ISSUE TITLE
Typo on the last post

### ISSUE THREAD

**Issue by fBedecarrats** [ThinkR-open/golemverse.org#32]
Hello,
On your last post, I think that the first sentence "The new version of `{golem}` (`0.3.1`) **have** been available on CRAN `r emo::ji("tada")` for about a month now" should read "The new version of `{golem}` (`0.3.1`) **has** been available on CRAN `r emo::ji("tada")` for about a month now.".
Best regards
FB

**Comment by ColinFay** [comment]
Corrected, thanks 🙏 😊
