### ISSUE TITLE
Mettre correctement documentation

### ISSUE THREAD

**Issue by Cervangirard** [ThinkR-open/golemverse.org#4]
![image](https://user-images.githubusercontent.com/37626302/71258823-61d8e800-2337-11ea-9aac-91983cedf942.png)

**Comment by Cervangirard** [comment]
Ca depend de la taille de l'écran certe mais la mon écran est un 13 pouce, donc ça va impacter pas mal de personnes quand même ce documentation tout moche

**Comment by statnmap** [comment]
Renamed as "Resources"
